const articles = [
    {
        "title": "Which tourist attraction in your city would you recommend to your colleagues?",
        "content": "I currently live in Hangzhou, China. I would definitely recommend the West Lake to foreign colleagues for several reasons. First, it's Hangzhou's most iconic scenic spot with a rich cultural heritage. Many ancient poets, including the famous Su Dongpo, were inspired by its beauty and wrote classic poems about it. Second, its central location makes it very accessible – no matter where your hotel is, you can reach it within an hour. Additionally, nearby attractions like Leifeng Tower and Longjing Village offer more things to explore, so you can relax and experience more after visiting the lake."
    },
    {
        "title": "What would you like to do if you had a day off tomorrow?",
        "content": "If I had a day off tomorrow, I would definitely visit West Lake. Since I currently live in Hangzhou, it is very accessible for me. First, I would spend some time at the lake itself. It is Hangzhou's most iconic scenic spot with a rich cultural heritage. I really enjoy the peaceful feeling of just being there, away from work. The natural beauty is a great way for me to relax and de-stress. After visiting the lake, I would explore some of the nearby attractions. For example, I could visit Leifeng Tower and Longjing Village. This would allow me to experience more of the local culture and scenery without feeling rushed. Finally, to finish the day, I would go to the supermarket to buy some fresh ingredients. I enjoy cooking, and preparing a meal for my family would make me very happy. Sharing a meal together is a great way to connect and a perfect end to a relaxing day off."
    },
    {
        "title": "Do you like making plans?",
        "content": "Yes, I do like making plans, for several reasons. First, making plans gives me a sense of control and security. When I have a plan, I feel more prepared and confident, whether it is for a major project at work or a simple weekend trip. For example, if I have a day off, I would plan to visit West Lake. I would think about what time to go, how to get there, and what to do afterwards. This way, I can make the most of my time and avoid feeling lost or overwhelmed. Second, planning helps me to be more efficient and productive. By breaking down a large task into smaller, manageable steps, I can focus on one thing at a time and track my progress. This is especially important at work, where I often deal with complex projects. A clear plan helps me stay organized and ensures that I meet my deadlines. Finally, I find the process of planning itself enjoyable. I like thinking about the future and imagining the different possibilities. It is a creative process that allows me to be proactive and shape my own experiences. For instance, when I plan a family dinner, I enjoy thinking about the menu, buying the ingredients, and cooking for my loved ones. The plan is not just about the food, but also about creating a happy and memorable experience for everyone."
    },
    {
        "title": "Are you busier now than when you were a student?",
        "content": "Yes, I am definitely busier now than when I was a student. My life has changed in several ways, and my responsibilities have grown significantly. First, my work requires a lot of my time and energy. As a student, my main focus was on studying and completing assignments. Now, I have to manage complex projects and meet strict deadlines. This often means I have to work long hours and I am always thinking about my work tasks, which makes me feel much more occupied. Second, I have more responsibilities in my personal life. For example, I enjoy cooking for my family, which is a rewarding but time-consuming activity. I need to plan meals, go to the supermarket, and spend time in the kitchen. As a student, I had fewer of these daily life responsibilities. My schedule was more flexible, and I had long vacations to relax and pursue my hobbies. Now, my free time is more limited, and I have to make plans carefully to have a good rest, like planning a visit to West Lake. In conclusion, because of the combination of a demanding job and more personal life duties, I am much busier now than I was in my student years."
    }
];