const samples = [
  {
    "title": "What's the best dining experience you have had so far? Please describe your experience and explain why it was the best.",
    "content": "One of the best dining experiences I've ever had was at a small restaurant in Santorini, Greece. What impressed me most was the beautiful view. When I went there, it was a beautiful summer evening, and the restaurant was right on the edge of a cliff, overlooking the sea. The view was so amazing, especially as the sun set and the sky turned pink. The food there was also good. The restaurant served Greek food, and everything was very fresh and tasty. We started with small dishes like a fresh salad. For the main course, I tried grilled octopus for the first time. I was unsure at first when I placed the order, but it turned out to be really good - it was cooked perfectly.The service there impressed me as well. The staff was friendly and made sure we were comfortable. They also explained the dishes and ingredients in a pretty comprehensive manner, which added to the experience. Looking back, what made this dining experience the best was the combination of delicious food, the great view, and warm service. It was a perfect evening that let me enjoy Greek culture and cuisine, and it's a memory I still cherish."
  },
  {
    "title": "Here is a picture showing the planning and progress of Project Lota, a new feature launch.",
    "content": "The Lota Project roadmap is divided into quarters and phases, with specific tasks and milestones outlined. The market research has already been finished in Phase 1 by March, with 10 thousand survey feedback collected. In Phase 2, we first focused on prototype development, which has already been completed by 75% but actually delayed by 2 weeks. There is also targeted iteration work left to be done in Phase 2. At the current moment, we are carrying out internal testing in Phase 3, progressing slowly and currently at 10% completion. The goal for this phase is to test with 10 thousand users. Looking ahead, Phase 4 will be the final phase before our launch in late June. It'll be about launch preparation and has not yet started."
  },
  {
    "title": "ROI is the only way to measure a project's success. Do you agree? How would you assess the benefits of projects you work on",
    "content": "I don’t agree that ROI (Return on Investment) is the only way to measure a project's success. While ROI is an important metric, especially in business, it doesn’t capture all the aspects that make a project successful. Let me explain why and how I would assess the benefits of projects. First, ROI focuses mainly on financial returns, but not all projects are about making money directly. For example, in an internet company, we might work on projects that improve user experience or build brand reputation. Let’s say we develop a new feature that makes our app easier to use. This might not bring immediate revenue, but it can increase user satisfaction and retention, which are crucial for long-term success. If we only look at ROI, we might miss the value of these potential benefits. Second, some projects have strategic importance that isn’t reflected in short-term financial gains. For instance, if we invest in a new technology that doesn’t pay off right away but make us an industry leader, the long-term benefits could be huge. Look at companies that started using AI or cloud computing early. They didn't make money right away, but later, these choices helped them beat their competitors. So, how would I assess the benefits of projects? I would use a combination of metrics. Besides ROI, I would look at user engagement, customer satisfaction, and how well the project aligns with our company’s long-term goals. For example, if we launch a new feature, I would track how many users are using it, how it affects their overall experience, and whether it helps us attract new users or retain existing ones. I would also consider feedback from users and stakeholders to understand the broader impact. In conclusion, while ROI is a useful metric, it’s not the only way to measure success. A broader view, considering both financial and non-financial factors, gives a better picture of a project’s true value."
  }
];